# This compose file is meant to spin up a copy of all supported database vendors + Redis and S3 (Minio).
# For production use see the docker compose file example in the docs:
#     https://docs.directus.io/self-hosted/docker-guide.html#example-docker-compose
#
# ONLY FOR DEBUGGING. THIS IS NOT INTENDED FOR PRODUCTION USE.
#
# Ports:
#   MS SQL: 5103
#   Redis: 5105
#   Minio (S3): 5106
#   Keycloak: 5110
#   Minio Admin: 5112
# #
# Credentials:
#   MS SQL:
#     User: sa
#     Password: Test@123
#
#   #   Redis:
#   #     n/a
#   #
#
#   Minio:
#     Key: minioadmin
#     Secret: minioadmin
#     # (Make sure to set S3_FORCE_PATH_STYLE to true)
#
#   Keycloak:
#     User: admin
#     Password: secret

version: '3.8'

services:
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Test@123
  #   ports:
  #     - 5103:1433

  # mysql:
  #   image: mysql:8
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '123456'
  #     MYSQL_DATABASE: 'ql_phapche'
  #   ports:
  #     - 5101:3306
  #   cap_add:
  #     - SYS_NICE

  postgres:
    image: postgres:16.2-alpine
    platform: linux/arm64
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: directus
    ports:
      - 5100:5432

  redis:
    image: redis:6-alpine
    ports:
      - 5105:6379

  minio:
    image: minio/minio
    command: server /data/minio/ --console-address :9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 5106:9000
      - 5112:9001

  # keycloak:
  #   image: jboss/keycloak
  #   environment:
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: secret
  #     DB_ADDR: ''
  #     DB_VENDOR: h2
  #   ports:
  #     - 5110:8080

  # directus:
  #   image: directus/directus:10.10.1
  #   ports:
  #     - 8055:8055
  #   volumes:
  #     # - ./database:/directus/database
  #     - ./uploads:/directus/uploads
  #     # - ./extensions:/directus/extensions
  #   environment:
  #     KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
  #     SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
  #
  #     # DB_CLIENT: 'mssql'
  #     # DB_HOST: 'mssql'
  #     # DB_PORT: '1433'
  #     # DB_DATABASE: 'ql_phapche'
  #     # DB_USER: 'sa'
  #     # DB_PASSWORD: 'Test@123'
  #     DB_CLIENT: 'pg'
  #     DB_HOST: 'postgres'
  #     DB_PORT: '5432'
  #     DB_DATABASE: 'directus'
  #     DB_USER: 'postgres'
  #     DB_PASSWORD: 'postgres'
  #
  #     CACHE_ENABLED: 'true'
  #     CACHE_STORE: 'redis'
  #     REDIS: 'redis://redis:6379'
  #
  #     STORAGE_LOCATIONS: s3
  #     STORAGE_S3_DRIVER: s3
  #     STORAGE_S3_KEY: 'mNLrcgKZ1kgYst8a3XEi'
  #     STORAGE_S3_SECRET: 'tvMzXQl0YouJTnV6NuhFsr5cVQ51q5gI65Ki0pCM'
  #     STORAGE_S3_REGION: 'us-east-1'
  #     STORAGE_S3_BUCKET: 'phapche'
  #     STORAGE_S3_ENDPOINT: 'http://minio:9000'
  #     STORAGE_S3_FORCE_PATH_STYLE: 'true'
  #
  #     ADMIN_EMAIL: 'phapche@hcmpc.com.vn'
  #     ADMIN_PASSWORD: 'EVNHCMC@2024'
  #
  #     WEBSOCKETS_ENABLED: 'true'
